release: release version 0.8.0
martinvonz/jj pull request #1827
Opened 2023-07-09 05:50 UTC by martinvonz

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

2023-07-09 05:57 UTC, martinvonz commented
This should be ready to merge, but we can wait for a week or so if we want to see if we discover any problems with new crates names that we want to fix before we cut a release.

2023-07-13 07:56 UTC, omasanori commented on README.md
> +![](https://img.shields.io/github/license/martinvonz/jj) ![](https://img.shields.io/github/v/release/martinvonz/jj) ![](https://img.shields.io/github/release-date/martinvonz/jj) ![](https://img.shiel
```suggestion
![](https://img.shields.io/github/license/martinvonz/jj) ![](https://img.shields.io/github/v/release/martinvonz/jj) ![](https://img.shields.io/github/release-date/martinvonz/jj) ![](https://img.shields.io/crates/v/jj-cli)
```

2023-07-13 07:58 UTC, omasanori requested changes
I have a nitpick. Thank you for your effort and I can't wait a new version!

2023-07-16 06:33 UTC, martinvonz commented on README.md
> +![](https://img.shields.io/github/license/martinvonz/jj) ![](https://img.shields.io/github/v/release/martinvonz/jj) ![](https://img.shields.io/github/release-date/martinvonz/jj) ![](https://img.shiel
Good catch! Fixed.

2023-07-16 16:18 UTC, omasanori approved these changes
Thanks for your response!

2023-07-16 20:22 UTC, martinvonz commented
> This should be ready to merge, but we can wait for a week or so if we want to see if we discover any problems with new crates names that we want to fix before we cut a release.

It's now been a week, so I guess I'll go ahead and merge this and start the release.

2023-07-16 20:37 UTC, martinvonz commented
> It's now been a week, so I guess I'll go ahead and merge this and start the release.

Once it's been approved by someone with write access, that is :)

2023-07-16 20:40 UTC, PhilipMetzger approved these changes
:-), atleast a contribution for `0.8`

2023-07-16 20:40 UTC, merged