README tweaks
martinvonz/jj pull request #234
Opened 2022-04-23 16:43 UTC by jaraco

I'm getting started with jj and had a couple of editorial comments and a lesson for xonsh that I've proposed here. I've not made changes to the CHANGELOG, as I suspect edits of this sort don't require changelog entries.

2022-04-23 16:52 UTC, martinvonz commented
Thanks! I just had a minor comment on the first commit.

2022-04-23 17:15 UTC, martinvonz requested changes

2022-04-25 13:13 UTC, jaraco commented on README.md
> +[^native-backend]: There's currently no practical reason to use the native
I found the "currently practically" difficult to parse, especially as adverbs on "is" with a negated subject. I can try another phrasing, which may alleviate my confusion.

2022-04-26 22:08 UTC, martinvonz commented on README.md
> +[^native-backend]: There's currently no practical reason to use the native
Thanks for the updated version. (Sorry, didn't notice it until now.)

2022-04-26 23:31 UTC, martinvonz approved these changes

2022-04-26 23:31 UTC, merged