docs: document `git.fetch` and `git.push` config options
martinvonz/jj pull request #2994
Opened 2024-02-08 21:51 UTC by thoughtpolice

Someone on Discord asked this exact question, but these options apparently weren't documented when they were added in the `0.7.0` release.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

2024-02-08 21:55 UTC, PhilipMetzger requested changes
Small things for now, but after that it looks great to me.

2024-02-08 21:55 UTC, PhilipMetzger commented on docs/config.md
> +```toml
Nit: since you use the command use shell here and provide a example with toml.

2024-02-08 21:55 UTC, PhilipMetzger commented on docs/config.md
> +jj config set --repo git.push "github"
Ditto.

2024-02-08 21:55 UTC, PhilipMetzger commented on docs/config.md
> +By default, the default remote used for `jj git fetch` and `jj git push` is the
Nit: Sentence can be improved, "By default the remote used for ... is the remote called origin just like Git."

2024-02-08 21:55 UTC, PhilipMetzger commented on docs/config.md
> +To change this behavior, you can modify the (repository) configuration variable
Nit: Maybe link the repo configuration here?

2024-02-08 21:56 UTC, PhilipMetzger commented
I forgot a thing, put the default configuration as a comment in `config.toml`.

2024-02-08 22:55 UTC, martinvonz approved these changes

2024-02-08 22:55 UTC, martinvonz commented on docs/config.md
> +called `"origin"`, just like in Git. Sometimes this is undesirable, e.g. when
nit: If there's only one remote, we use that for fetch/push. If there are multiple, we use "origin" by default

2024-02-09 03:02 UTC, ilyagr reviewed
Thank you!

2024-02-09 03:02 UTC, ilyagr commented on docs/config.md
> +push to a different remote:
If this does *not* work with multiple remotes, and `git.fetch` does, we should mention it here: "Unlike `git.fetch`, `git.push` currently cannot be set to multiple remotes"

2024-02-09 17:35 UTC, PhilipMetzger approved these changes
LG

2024-02-09 17:35 UTC, PhilipMetzger commented on docs/config.md
> +```
Nit: `mkdocs` needs a language, so add `sh` here.

2024-02-09 17:35 UTC, PhilipMetzger commented on docs/config.md
> +```
Ditto

2024-02-09 18:02 UTC, thoughtpolice commented on docs/config.md
> +jj config set --repo git.fetch '["origin", "upstream"]'
Yes, from reading the code it should work just fine; after all, we already have `--all-remotes`, so this is just a specialization of that.

2024-02-09 18:03 UTC, merged